/* tslint:disable */
/* eslint-disable */
/**
 * Gently OpenAPI
 * OpenAPI for interacting with our Gently inventory management system.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

