FROM --platform=linux/amd64 node:22.12-alpine as builder

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
RUN npm install --verbose

# No need to copy the source code here since we're mounting the source code from the host
# Copy the source code from the host -> solved by volume mounting in docker-compose.yml
# COPY . .

EXPOSE 4000

CMD ["npm", "run", "start:local"]