import { NodeLogger } from '@unconventional-code/observability-sdk';
import { UserModel } from '@unconventional-jackson/gently-database-service';
import {
  AuthChangePasswordRequestBody,
  ErrorResponse,
} from '@unconventional-jackson/gently-openapi-service';
import { compare, hash } from 'bcrypt';
import { Request, Response } from 'express';

/**
 * TODO: Not generated by swagger?
 */
export type AuthChangePasswordResponseBody = {
  message: string;
};

export async function changePassword(
  req: Request<unknown, unknown, AuthChangePasswordRequestBody>,
  res: Response<AuthChangePasswordResponseBody | ErrorResponse>
) {
  const log = new NodeLogger({
    correlation: res.locals.correlation,
    name: 'views/Auth/changePassword',
  });

  try {
    if (!req.body.email) {
      res.status(400).json({ message: 'Missing email in the body.' });
      return;
    }
    const email = req.body.email;

    if (!req.body.current_password) {
      res.status(400).json({ message: 'Missing current_password in the body.' });
      return;
    }
    const currentPassword = req.body.current_password;

    if (!req.body.new_password) {
      res.status(400).json({ message: 'Missing new_password in the body.' });
      return;
    }
    const newPassword = req.body.new_password;

    const user = await UserModel.findOne({ where: { email } });

    if (!user) {
      res.status(400).json({ error: 'User not found' });
      return;
    }

    if (!user.auth_password_hash) {
      res.status(400).json({ error: 'User has no password' });
      return;
    }

    const passwordMatch = await compare(currentPassword, user.auth_password_hash);
    if (!passwordMatch) {
      res.status(400).json({ error: 'Password does not match' });
      return;
    }

    const authPasswordHash = await hash(newPassword, 10);
    await user.update({
      auth_password_hash: authPasswordHash,
    });

    res.status(200).json({ message: 'Password updated' });
    return;
  } catch (error) {
    log.error(error);
    res.status(500).json({ error: String(error) });
  }
}
